version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - n 16
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - echo Running lint...
      - npm run lint
      - echo Running tests...
      - npm run test
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - dist
    - node_modules
    - package.json
    - package-lock.json
    - nest-cli.json
